### ISSUE TITLE
Scaling a component does not scale it's children.

### ISSUE THREAD

**Issue by LordSaad44** [TeamWizardry/LibrarianLib#12]
It's understandable that the bounding box of a component can alloy components outside of it, but there should be an option that clamps and scales bounding boxes of children from the parent.

To rephrase: scaling a component does not interact with it's children as it should, but there should be an option that forces children to follow scalings and positionings.

**Comment by thecodewarrior** [comment]
Fixed in 9740267e223417a517dc5c40dd35307cd73e4560.

Components now have `childTranslate` and `childScale` fields to control positioning and scaling of children. This means that `ComponentScrolledView` will be either phased out or modified to handle more of the business logic of scrolled views, since it no longer has to manage the scaling and movement of children.
