### ISSUE TITLE
Player cannot join the Catserver/Mohist

### ISSUE THREAD

**Issue by Jacky10X** [TeamWizardry/LibrarianLib#129]
Server Software version: CatServer/Mohist 1.12.2 
From:https://github.com/Luohuayu/CatServer
From2:https://github.com/Mohist-Community/Mohist

Server Error: https://pastebin.com/YKc87Xdi 
(Sorry for the Chinese language because I am not using the English language and I don't know how to change the output to English) 
Client Error: https://ibb.co/zxB6dsz

When the player joins the game, they cannot connect to the server and show the error but the server keeps running.

**Comment by Bluexin** [comment]
At least two reasons that could cause this : 
 - an asm edit from liblib is not compatible with CatServer
 - other random incompatibility with CatServer

We don't support CatServer because of how different it is from regular Forge, and we don't have the time and energy to look into supporting it unfortunately.
We'd be open to contributions to fix this however !

**Comment by thecodewarrior** [comment]
1.12 is no longer going to be supported, save for any critical bugfixes.
