### ISSUE TITLE
Read reflection data from mappings

### ISSUE THREAD

**Issue by Bluexin** [TeamWizardry/LibrarianLib#54]
Deobf vs obf names should be read at runtime from mappings if they're installed. This would improve compatibility accross dev envs with different mappings.

(making an issue so I don't forget about it ;-; )

**Comment by thecodewarrior** [comment]
This appears to be possible using the same system that ASM uses. The implementation used from ASM can be found in `ASMAPI.mapMethod/mapField`. It may be best to actually use those methods, as opposed to copying their implementation, since `ASMAPI` is used from within ASM code, so the api will be more stable.
