### ISSUE TITLE
Add support for wildcard types in Saving feature

### ISSUE THREAD

**Issue by Bluexin** [TeamWizardry/LibrarianLib#79]
Trying to save any generic type using wildcard type (Java's `? extends X` or `? super X` and Kotlin's `out X` and `in X`) currently creates a FieldTypeError.
Java reflect stl represents them using instances of `WildcardType`.

**Comment by thecodewarrior** [comment]
So the issue is that it crashes, not that you want to (de)serialize wildcard types? I suppose wildcards could be done with `@Dyn` (sorry to whoever `@DYN` is for the ping) as I don't believe it requires a serializer outside of the dynamic ones, but if anything tried to grab a wildcard serializer it would immediately fail to and crash.

**Comment by Bluexin** [comment]
In my specific use case the generic type is a final class, but in a kt List (which has out variance), however it could be useful to support dynamic for it.

**Comment by thecodewarrior** [comment]
I could make it serialize as the bound, or I think you could use [`@JvmSuppressWildcards`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-suppress-wildcards/index.html)
