### ISSUE TITLE
[4.17] Player being kicked from server

### ISSUE THREAD

**Issue by kreezxil** [TeamWizardry/LibrarianLib#81]
## the crash
this is the error from the console.

https://pastebin.com/gxwbtG17

## Logs:
Latest: http://paste.ubuntu.com/p/pPzwHDC52Z/
debug: http://paste.ubuntu.com/p/R7Zkj6Xmvn/

## Modlist

http://paste.ubuntu.com/p/6cVsxHVfBF/

**Comment by thecodewarrior** [comment]
This is due to a mod using a method that had accidentally been removed. Specifically `com.teamwizardry.librarianlib.features.helpers.ItemNBTHelper.removeEntry(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V`. We've gone ahead and scanned the jar for any other accidental deletions, and the fix should be trivial for the next patch.

**Comment by kreezxil** [comment]
ok, just got the crash again this time because something is in the world.

https://pastebin.com/gV1anwak

what is the eta on the next patch?
Can I roll this down a version and psideas still work?

**Comment by thecodewarrior** [comment]
Yeah, rolling back will probably work, though I would make a backup of your world beforehand just in case. We don’t have an eta on the patch, but ideally it’ll be out in the next few days.

**Comment by kreezxil** [comment]
The roll down worked great.
